const express = require('express');
const Merchant = require('../models/merchant');
const { MERCHANT_STATUS, SETTLEMENT } = require('../utils/constants/merchant');

const router = new express.Router();

router.post('/register', async (req, res) => {
    const isContainMid = Object.keys(req.body).includes('mid');

    if (isContainMid) {
        return res.status(400).send('Mid is autogenerated. Please remove mid.');
    }

    const merchant = new Merchant(req.body);
    try {
        await merchant.save();
        res.status(201).send(merchant);
    } catch (err) {
        res.status(400).send(err);
    }
});

module.exports = router;
